/* 
VARIAVEIS SÃO "RECIPIENTES" ONDE PODEMOS ARMAZENAR INFORMAÇÕES QUE PODEM VARIAR, OU SEJA, PODEM TER QUALQUER TIPO DE VALOR. 

NO JAVASCRIPT TEMOS 3 PALAVRAS-CHAVES PARA DECLARAR VARIÁVEIS:
-> VAR
-> LET
-> CONST
*/

var pote="Bombom";
alert(pote);